import { build } from "esbuild";
import sharp from "sharp";
import { mkdir, copyFile, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
const root = fileURLToPath(new URL("../", import.meta.url));
await mkdir(join(root, "dist"), { recursive: true });
await build({ entryPoints: [join(root, "src/main.mjs")], outfile: join(root, "dist/main.cjs"), bundle: true, platform: "node", format: "cjs", target: "node24", external: ["electron", "electron-updater"], sourcemap: false });
for (const name of ["preload.cjs", "runtime-hook.cjs", "startup.html", "startup.js"]) await copyFile(join(root, "src", name), join(root, "dist", name));
// The visual is generated by the image model; only resize/encode it for Windows.
const iconSource = join(root, "assets/icon.png");
const png = await sharp(iconSource).resize(256, 256).png().toBuffer();
await writeFile(join(root, "dist/icon.png"), png);
const sizes = [16, 24, 32, 48, 64, 128, 256];
const frames = await Promise.all(sizes.map((size) => sharp(iconSource).resize(size, size).png().toBuffer()));
const header = Buffer.alloc(6 + 16 * sizes.length);
header.writeUInt16LE(1, 2);
header.writeUInt16LE(sizes.length, 4);
let offset = header.length;
for (const [index, size] of sizes.entries()) {
  const entry = 6 + index * 16;
  header[entry] = header[entry + 1] = size === 256 ? 0 : size;
  header.writeUInt16LE(1, entry + 4);
  header.writeUInt16LE(32, entry + 6);
  header.writeUInt32LE(frames[index].length, entry + 8);
  header.writeUInt32LE(offset, entry + 12);
  offset += frames[index].length;
}
await writeFile(join(root, "assets/icon.ico"), Buffer.concat([header, ...frames]));
const workspace = JSON.parse(await readFile(join(root, "../../package.json"), "utf8"));
const desktop = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
if (workspace.version !== desktop.version) throw new Error("Desktop package version must match the workspace version");
const releaseNotes = await readFile(join(root, "../../docs/releases/v" + workspace.version + ".md"), "utf8");
if (!releaseNotes.trim()) throw new Error("Versioned release notes must not be empty");
await writeFile(join(root, "dist/release-notes.md"), releaseNotes);
// --dir does not generate updater metadata. NSIS may augment this with signing
// policy later; every distribution must still include the base feed and cache.
await writeFile(join(root, "dist/app-update.yml"), JSON.stringify({ ...desktop.build.publish, updaterCacheDirName: "@super-canvasdesktop-updater" }));
console.log("Desktop shell built.");
