// Extracted from official per-model documents, fresh GET 2026-10-07;
// individually rechecked/new contracts carry their own checkedAt date.
// Source: https://ai.cangyuansuanli.cn/docs-static/models/{id}.json
// Public documentation does not grant a Key permission to use a model.
export interface CangyuanVideoContractData {
 checkedAt?: string; facePolicy?: "open"; fixedResolution?: string;
 fields: readonly string[];
 parameters: readonly { key: string; description: string; values?: readonly (string | number)[]; min?: number; max?: number; default?: string | number | boolean }[];
 references: { images: number | null; videos: number | null; audios: number | null };
 frames: boolean; framePairRequired: boolean; allowFrameMediaMix: boolean;
 inputMimeTypes?: { image?: readonly string[]; video?: readonly string[]; audio?: readonly string[] }; maxInputBytes?: { image?: number; video?: number; audio?: number };
 videoObjects?: boolean; maxTotalInputVideoDurationSeconds?: number; maxInputAssets?: number;
 minInputVideoDurationSeconds?: number; maxInputVideoDurationSeconds?: number; minTotalInputVideoDurationSeconds?: number;
 minInputAudioDurationSeconds?: number; maxInputAudioDurationSeconds?: number;
 maxOutputAndInputVideoDurationSeconds?: number; durationMaxWithReferenceVideo?: number; requiresImageWithAudio?: boolean;
 maxTotalInputAudioDurationSeconds?: number; approximateDurationSeconds?: number; maxPromptCharacters?: number;
}
export const CANGYUAN_CURRENT_VIDEO_CONTRACTS: Readonly<Record<string, CangyuanVideoContractData>> = {
 "sd8-seedance-2.5-s": {
  checkedAt: "2026-10-08", facePolicy: "open", fixedResolution: "720p",
  fields: ["duration", "aspect_ratio", "reference_image_urls", "reference_videos", "reference_audios"],
  parameters: [
   { key: "duration", description: "时长固定 30 秒，成片固定 720p；不要发送 resolution。", values: [30] },
   { key: "aspect_ratio", description: "画幅比例，可选 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。", values: ["21:9", "16:9", "4:3", "1:1", "3:4", "9:16"] },
  ],
  references: { images: 30, videos: 10, audios: 10 },
  frames: false, framePairRequired: false, allowFrameMediaMix: false,
 },
 "minimax-h3-2k": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，5–15。","min":5,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4。","values":["16:9","9:16","1:1","4:3","3:4"]},{"key":"resolution","description":"清晰度，固定 2K。","values":["2K"]}],"references":{"images":5,"videos":3,"audios":3},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false,"maxTotalInputVideoDurationSeconds":15},
 "seedance-2.0-720p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":9,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "seedance-2.0-1080p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 1080p。","values":["1080p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":5,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":5,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "wan3.0-15s": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数。"},{"key":"aspect_ratio","description":"画幅比例。"},{"key":"resolution","description":"清晰度。"}],"references":{"images":null,"videos":null,"audios":null},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "wan3.0-video": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，5–30。","min":5,"max":30},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4。","values":["16:9","9:16","1:1","4:3","3:4"]},{"key":"resolution","description":"清晰度，可选 480p / 720p / 1080p。","values":["480p","720p","1080p"]}],"references":{"images":10,"videos":5,"audios":5},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "grok-video": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 6 / 8 / 10 / 12 / 15。","values":[4,6,8,10,12,15]},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。不要传 4:3 / 3:4 / 2:3 / 3:2。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]}],"references":{"images":7,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "grok-video-1.5": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 6 / 8 / 10 / 12 / 15。","values":[4,6,8,10,12,15]},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。不要传 4:3 / 3:4 / 2:3 / 3:2。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]}],"references":{"images":7,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "grok-imagine-video": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，1–15。省略时按 6 秒出片。","min":1,"max":15,"default":6},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。省略默认 16:9。","values":["16:9","9:16","1:1"],"default":"16:9"},{"key":"resolution","description":"清晰度，可选 480p / 720p。省略默认 480p。不同清晰度单价不同，以模型广场为准。","values":["480p","720p"],"default":"480p"}],"references":{"images":1,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "grok-imagine-video-1.5": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，1–15。省略时按 6 秒出片。","min":1,"max":15,"default":6},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。省略默认 16:9。","values":["16:9","9:16","1:1"],"default":"16:9"},{"key":"resolution","description":"清晰度，可选 480p / 720p / 1080p。省略默认 480p。不同清晰度单价不同，以模型广场为准。","values":["480p","720p","1080p"],"default":"480p"}],"references":{"images":7,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "grok-imagine-video-6s": {"fields":["aspect_ratio","reference_image_urls"],"parameters":[{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1。省略默认 9:16。","values":["16:9","9:16","1:1"],"default":"9:16"}],"references":{"images":7,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":4,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":4,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "veo-3.1": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","reference_image_urls","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 6 / 8。","values":[4,6,8]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。","values":["16:9","9:16"]},{"key":"resolution","description":"清晰度，可选 720p / 1080p。","values":["720p","1080p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"},{"key":"seed","description":"可选整数种子。"}],"references":{"images":3,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "veo-3.1-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 6 / 8。","values":[4,6,8]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。","values":["16:9","9:16"]},{"key":"resolution","description":"清晰度，可选 720p / 1080p。","values":["720p","1080p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"},{"key":"seed","description":"可选整数种子。"}],"references":{"images":0,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "kling-3.0": {"fields":["duration","aspect_ratio","generate_audio","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，3–15。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 1:1 / 9:16。","values":["16:9","1:1","9:16"]},{"key":"generate_audio","description":"是否生成音频，true / false。默认 true。","default":true}],"references":{"images":1,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "kling-3.0-pro": {"fields":["duration","aspect_ratio","generate_audio","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，3–15。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 1:1 / 9:16。","values":["16:9","1:1","9:16"]},{"key":"generate_audio","description":"是否生成音频，true / false。默认 true。","default":true}],"references":{"images":4,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "kling-3.0-omni": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，5–15。","min":5,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 1:1 / 9:16。","values":["16:9","1:1","9:16"]},{"key":"resolution","description":"清晰度，可选 720p / 1080p。","values":["720p","1080p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"},{"key":"seed","description":"可选整数种子。"}],"references":{"images":0,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "gemini-omni-flash": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，仅 4 / 6 / 8 / 10。","values":[4,6,8,10]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。","values":["16:9","9:16"]},{"key":"resolution","description":"清晰度，可选 720p。","values":["720p"]}],"references":{"images":1,"videos":0,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false,"checkedAt":"2026-10-09"},
 "happyhouse-1.0": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","first_image_url"],"parameters":[{"key":"duration","description":"时长秒数，3–15。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。","values":["16:9","9:16"]},{"key":"resolution","description":"清晰度，可选 HD / FHD。","values":[]}],"references":{"images":9,"videos":1,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false},
 "happyhouse-1.1": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","first_image_url"],"parameters":[{"key":"duration","description":"时长秒数，3–15。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。","values":["16:9","9:16"]},{"key":"resolution","description":"清晰度，可选 HD / FHD。","values":[]}],"references":{"images":9,"videos":0,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false},
 "happyhorse-1.1": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，3–15。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9 / 9:21 / 5:4 / 4:5。","values":["16:9","9:16","1:1","4:3","3:4","21:9","9:21","5:4","4:5"]},{"key":"resolution","description":"清晰度，可选 720p / 1080p。也认 HD（720p）、FHD（1080p）。缺省 1080p。","values":["720p","1080p"],"default":"1080p"}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "minimax-h3-768p": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，5–15。","min":5,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4。","values":["16:9","9:16","1:1","4:3","3:4"]},{"key":"resolution","description":"清晰度，固定 768p。","values":["768p"]}],"references":{"images":5,"videos":3,"audios":3},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false,"maxTotalInputVideoDurationSeconds":15},
 "omni-fast": {"fields":["duration","aspect_ratio","reference_image_urls","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"可省略。当前成片约 10 秒；传入其他秒数通常不会改变成片时长。"},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。省略默认 16:9。","values":["16:9","9:16"],"default":"16:9"}],"references":{"images":5,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false,"approximateDurationSeconds":10},
 "omni-fast-no-water": {"fields":["duration","aspect_ratio","reference_image_urls","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"可省略。当前成片约 10 秒；传入其他秒数通常不会改变成片时长。"},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。省略默认 16:9。","values":["16:9","9:16"],"default":"16:9"}],"references":{"images":5,"videos":0,"audios":0},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false,"approximateDurationSeconds":10},
 "omni-v2v": {"fields":["duration","aspect_ratio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"可省略。当前成片约 10 秒；传入其他秒数通常不会改变成片时长。"},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。省略默认 16:9。","values":["16:9","9:16"],"default":"16:9"}],"references":{"images":5,"videos":2,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"approximateDurationSeconds":10},
 "omni-v2v-no-water": {"fields":["duration","aspect_ratio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"可省略。当前成片约 10 秒；传入其他秒数通常不会改变成片时长。"},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。省略默认 16:9。","values":["16:9","9:16"],"default":"16:9"}],"references":{"images":5,"videos":2,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"approximateDurationSeconds":10},
 "sd4-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":4,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd4-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":4,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd4-seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":4,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd4-seedance-2.5-480p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–30。","min":4,"max":30},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 480p。","values":["480p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":30,"videos":10,"audios":10},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd4-seedance-2.5-720p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数。无参考视频 4–29，有参考视频 4–18。","min":4,"max":29},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":30,"videos":10,"audios":10},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false,"durationMaxWithReferenceVideo":18,"maxInputVideoDurationSeconds":30.2,"maxTotalInputVideoDurationSeconds":30.2,"maxInputAudioDurationSeconds":30.2,"maxTotalInputAudioDurationSeconds":30.2,"checkedAt":"2026-10-09"},
 "sd5-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。","values":["21:9","16:9","4:3","1:1","3:4","9:16"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"},{"key":"seed","description":"可选整数种子。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd5-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。","values":["21:9","16:9","4:3","1:1","3:4","9:16"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"},{"key":"seed","description":"可选整数种子。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd6-seedance-2.0-720p": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 8 / 10 / 12 / 15。","values":[4,5,6,8,10,12,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4。","values":["16:9","9:16","1:1","4:3","3:4"]},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]}],"references":{"images":9,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd6-seedance-2.0-1080p": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 8 / 10 / 12 / 15。","values":[4,5,6,8,10,12,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4。","values":["16:9","9:16","1:1","4:3","3:4"]},{"key":"resolution","description":"清晰度，固定 1080p。","values":["1080p"]}],"references":{"images":9,"videos":3,"audios":1},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd7-seedance-2.0-720p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":5,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "sd7-seedance-2.0-1080p": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，可选 4 / 5 / 6 / 7 / 8 / 9 / 10 / 11 / 12 / 13 / 14 / 15。","values":[4,5,6,7,8,9,10,11,12,13,14,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9"]},{"key":"resolution","description":"清晰度，固定 1080p。","values":["1080p"]},{"key":"generate_audio","description":"是否生成音频，true / false。"}],"references":{"images":5,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "sd8-seedance-2.0-fast": {"fields":["duration","aspect_ratio","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，1–15。","min":1,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。","values":["21:9","16:9","4:3","1:1","3:4","9:16"]}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "sd8-seedance-2.5": {"fields":["duration","aspect_ratio","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，固定 30。","values":[30]},{"key":"aspect_ratio","description":"画幅比例，可选 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。","values":["21:9","16:9","4:3","1:1","3:4","9:16"]}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "doubao-seedance-2-0-260128": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","face_mode","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"整数秒，4–15。不传按 4。不要传字符串，不要传 4 以下或 15 以上。","min":4,"max":15,"default":4},{"key":"aspect_ratio","description":"画幅。可选 16:9 / 9:16 / 1:1 / 21:9 / 4:3 / 3:4。不传按 16:9。不要用 size 表达同一设置。","values":["16:9","9:16","1:1","21:9","4:3","3:4"],"default":"16:9"},{"key":"resolution","description":"只能 720p。传其他值也会按 720p 处理。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频。true 或 false，按需发送。"},{"key":"seed","description":"随机种子，整数。需要复现同一构图时再传。"},{"key":"face_mode","description":"人脸代审核。选这条路时传 true，参考图用公网 https。走素材库、已经写 asset:// 时不要传这个字段。不保证一定过审。"}],"references":{"images":null,"videos":null,"audios":null},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "doubao-seedance-2-0-fast-260128": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","face_mode","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"整数秒，4–15。不传按 4。不要传字符串，不要传 4 以下或 15 以上。","min":4,"max":15,"default":4},{"key":"aspect_ratio","description":"画幅。可选 16:9 / 9:16 / 1:1 / 21:9 / 4:3 / 3:4。不传按 16:9。不要用 size 表达同一设置。","values":["16:9","9:16","1:1","21:9","4:3","3:4"],"default":"16:9"},{"key":"resolution","description":"只能 720p。传其他值也会按 720p 处理。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频。true 或 false，按需发送。"},{"key":"seed","description":"随机种子，整数。需要复现同一构图时再传。"},{"key":"face_mode","description":"人脸代审核。选这条路时传 true，参考图用公网 https。走素材库、已经写 asset:// 时不要传这个字段。不保证一定过审。"}],"references":{"images":null,"videos":null,"audios":null},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "doubao-seedance-2-0-mini-260615": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","face_mode","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"整数秒，4–15。不传按 4。不要传字符串，不要传 4 以下或 15 以上。","min":4,"max":15,"default":4},{"key":"aspect_ratio","description":"画幅。可选 16:9 / 9:16 / 1:1 / 21:9 / 4:3 / 3:4。不传按 16:9。不要用 size 表达同一设置。","values":["16:9","9:16","1:1","21:9","4:3","3:4"],"default":"16:9"},{"key":"resolution","description":"只能 720p。传其他值也会按 720p 处理。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频。true 或 false，按需发送。"},{"key":"seed","description":"随机种子，整数。需要复现同一构图时再传。"},{"key":"face_mode","description":"人脸代审核。选这条路时传 true，参考图用公网 https。走素材库、已经写 asset:// 时不要传这个字段。不保证一定过审。"}],"references":{"images":null,"videos":null,"audios":null},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "doubao-seedance-2-5-260628": {"fields":["duration","aspect_ratio","resolution","generate_audio","seed","face_mode","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"整数秒，4–30。不传按 4。不要传字符串，不要传 4 以下或 30 以上。","min":4,"max":30,"default":4},{"key":"aspect_ratio","description":"画幅。可选 16:9 / 9:16 / 1:1 / 21:9 / 4:3 / 3:4。不传按 16:9。不要用 size 表达同一设置。","values":["16:9","9:16","1:1","21:9","4:3","3:4"],"default":"16:9"},{"key":"resolution","description":"只能 720p。传其他值也会按 720p 处理。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频。true 或 false，按需发送。"},{"key":"seed","description":"随机种子，整数。需要复现同一构图时再传。"},{"key":"face_mode","description":"人脸代审核。选这条路时传 true，参考图用公网 https。走素材库、已经写 asset:// 时不要传这个字段。不保证一定过审。"}],"references":{"images":null,"videos":null,"audios":null},"frames":true,"framePairRequired":true,"allowFrameMediaMix":false},
 "sd10-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","camera_movement","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，可选 5 / 10 / 15。","values":[5,10,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。不传时为 9:16。","values":["16:9","9:16","1:1","4:3","3:4","21:9"],"default":"9:16"},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"camera_movement","description":"镜头运动，可选 auto / fixed。","values":["auto","fixed"]}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"maxPromptCharacters":6000},
 "sd10-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","camera_movement","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，可选 5 / 10 / 15。","values":[5,10,15]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。不传时为 9:16。","values":["16:9","9:16","1:1","4:3","3:4","21:9"],"default":"9:16"},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"camera_movement","description":"镜头运动，可选 auto / fixed。","values":["auto","fixed"]}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"maxPromptCharacters":6000},
 "sd10-seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","camera_movement","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，可选 5 / 10。","values":[5,10]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。不传时为 9:16。","values":["16:9","9:16","1:1","4:3","3:4","21:9"],"default":"9:16"},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"camera_movement","description":"镜头运动，可选 auto / fixed。","values":["auto","fixed"]}],"references":{"images":9,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"maxPromptCharacters":6000},
 "sd10-seedance-2.5": {"fields":["duration","aspect_ratio","resolution","camera_movement","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，固定 30。","values":[30]},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9。不传时为 9:16。","values":["16:9","9:16","1:1","4:3","3:4","21:9"],"default":"9:16"},{"key":"resolution","description":"清晰度，固定 720p。","values":["720p"]},{"key":"camera_movement","description":"镜头运动，可选 auto / fixed。","values":["auto","fixed"]}],"references":{"images":30,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"maxPromptCharacters":6000},
 "niulai-pro": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，整数，范围 4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16 / 1:1 / 4:3 / 3:4 / 21:9 / adaptive。不传时为 16:9。","values":["16:9","9:16","1:1","4:3","3:4","21:9","adaptive"],"default":"16:9"},{"key":"resolution","description":"清晰度，可选 768p / 2k。不传时为 768p。","values":["768p","2k"],"default":"768p"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false,"maxTotalInputVideoDurationSeconds":15,"inputMimeTypes":{"image":["image/jpeg","image/png","image/webp"],"video":["video/mp4","video/quicktime"],"audio":["audio/mpeg","audio/mp4","audio/x-m4a","audio/wav","audio/x-wav"]},"maxTotalInputAudioDurationSeconds":15,"requiresImageWithAudio":true,"maxPromptCharacters":6000},
 "mm2-minimax-h3": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，4–15。不传时为 5。","min":4,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 768P / 2K。不传时为 768P。","values":["768P","2K"],"default":"768P"},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "mm2-minimax-h3-max": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，5–15。不传时为 5。","min":5,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 480P / 768P。不传时为 480P。","values":["480P","768P"],"default":"480P"},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "sd11-seedance-2.5": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，4–30。不传时为 5。","min":4,"max":30,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 480p / 720p / 1080p。不传时为 480p。","values":["480p","720p","1080p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":30,"videos":10,"audios":10},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "sd11-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，4–15。不传时为 7。","min":4,"max":15,"default":7},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 480p / 720p / 1080p。不传时为 480p。","values":["480p","720p","1080p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "sd11-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，4–15。不传时为 7。","min":4,"max":15,"default":7},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。不传时为 480p。","values":["480p","720p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "sd11-seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，4–15。不传时为 7。","min":4,"max":15,"default":7},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16 / 21:9 / adaptive。","values":["16:9","4:3","1:1","3:4","9:16","21:9","adaptive"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。不传时为 480p。","values":["480p","720p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "wan4-wan3.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，2–30。不传时为 5。","min":2,"max":30,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 adaptive / 16:9 / 9:16 / 1:1 / 4:3 / 3:4。不传时为 16:9。","values":["adaptive","16:9","9:16","1:1","4:3","3:4"],"default":"16:9"},{"key":"resolution","description":"清晰度，可选 480P / 720P / 1080P。不传时为 480P。","values":["480P","720P","1080P"],"default":"480P"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":10,"videos":5,"audios":5},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true},
 "kl1-kling-3.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","first_image_url","last_image_url","seed"],"parameters":[{"key":"duration","description":"时长秒数，3–15。不传时为 5。","min":3,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，仅文生生效，可选 16:9 / 9:16 / 1:1。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，可选 720p / 1080p。不传时为 720p。","values":["720p","1080p"],"default":"720p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true},{"key":"seed","description":"随机种子，非负整数。"}],"references":{"images":0,"videos":0,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false},
 "sd12-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 5。","min":4,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 16:9。带参考图或首尾帧时，画面常跟随素材。","values":["16:9","4:3","1:1","3:4","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 480p。可省略。","values":["480p"]},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true,"maxOutputAndInputVideoDurationSeconds":18,"maxInputBytes":{"image":31457280,"video":209715200,"audio":15728640},"inputMimeTypes":{"video":["video/mp4"]},"minInputVideoDurationSeconds":2,"maxInputVideoDurationSeconds":15,"maxTotalInputAudioDurationSeconds":15,"maxPromptCharacters":5000},
 "sd12-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 5。","min":4,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 16:9。带参考图或首尾帧时，画面常跟随素材。","values":["16:9","4:3","1:1","3:4","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 480p。可省略。","values":["480p"]},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true,"maxOutputAndInputVideoDurationSeconds":25,"maxInputBytes":{"image":31457280,"video":209715200,"audio":15728640},"inputMimeTypes":{"video":["video/mp4"]},"minInputVideoDurationSeconds":2,"maxInputVideoDurationSeconds":15,"maxTotalInputAudioDurationSeconds":15,"maxPromptCharacters":2000},
 "sd12-seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 5。","min":4,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 16:9。带参考图或首尾帧时，画面常跟随素材。","values":["16:9","4:3","1:1","3:4","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 480p。可省略。","values":["480p"]},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":true,"maxTotalInputVideoDurationSeconds":15,"maxInputBytes":{"image":31457280,"video":209715200,"audio":15728640},"inputMimeTypes":{"video":["video/mp4"]},"minInputVideoDurationSeconds":2,"maxInputVideoDurationSeconds":15,"maxTotalInputAudioDurationSeconds":15,"maxPromptCharacters":3800},
 "kl2-kling-3.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 3–15。不传时为 5。","min":3,"max":15,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 1:1 / 9:16。不传时为 16:9。带首尾帧时，画面常跟随素材。","values":["16:9","1:1","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 720p。可省略。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 false。需要配音时请显式传 true。","default":false}],"references":{"images":0,"videos":0,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false,"maxInputBytes":{"image":31457280},"maxPromptCharacters":2500},
 "wan5-wan3.0": {"fields":["duration","aspect_ratio","resolution"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 2–30。不传时为 5。","min":2,"max":30,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 16:9。","values":["16:9","4:3","1:1","3:4","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 480p。可省略。","values":["480p"]}],"references":{"images":0,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"maxPromptCharacters":20000},
 "ve1-veo-3.1-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"出片时长，只能是 4 / 6 / 8。不传时为 4。不要传 5 或其它整数。","values":[4,6,8],"default":4},{"key":"aspect_ratio","description":"画幅比例，可选 16:9 / 9:16。不传时为 16:9。带首尾帧时，画面常跟随素材。","values":["16:9","9:16"],"default":"16:9"},{"key":"resolution","description":"清晰度，固定 720p。可省略。","values":["720p"]},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":0,"videos":0,"audios":0},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false,"maxInputBytes":{"image":31457280},"maxPromptCharacters":2000},
 "sd13-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 8。","min":4,"max":15,"default":8},{"key":"aspect_ratio","description":"画幅比例，可选 auto / 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 auto。带参考图时画面常跟随素材。","values":["auto","21:9","16:9","4:3","1:1","3:4","9:16"],"default":"auto"},{"key":"resolution","description":"清晰度，可选 480p / 720p / 1080p / 4k。不传时为 480p。1080p 与 4k 同价。","values":["480p","720p","1080p","4k"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"minTotalInputVideoDurationSeconds":2,"maxTotalInputVideoDurationSeconds":15,"inputMimeTypes":{"image":["image/jpeg","image/png","image/webp"],"video":["video/mp4","video/quicktime"]},"maxInputBytes":{"image":31457280}},
 "sd13-seedance-2.0-fast": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 8。","min":4,"max":15,"default":8},{"key":"aspect_ratio","description":"画幅比例，可选 auto / 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 auto。带参考图时画面常跟随素材。","values":["auto","21:9","16:9","4:3","1:1","3:4","9:16"],"default":"auto"},{"key":"resolution","description":"清晰度，可选 480p / 720p。不传时为 480p。","values":["480p","720p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"minTotalInputVideoDurationSeconds":2,"maxTotalInputVideoDurationSeconds":15,"inputMimeTypes":{"image":["image/jpeg","image/png","image/webp"],"video":["video/mp4","video/quicktime"]},"maxInputBytes":{"image":31457280}},
 "sd13-seedance-2.0-mini": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–15。不传时为 8。","min":4,"max":15,"default":8},{"key":"aspect_ratio","description":"画幅比例，可选 auto / 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 auto。带参考图时画面常跟随素材。","values":["auto","21:9","16:9","4:3","1:1","3:4","9:16"],"default":"auto"},{"key":"resolution","description":"清晰度，可选 480p / 720p。不传时为 480p。","values":["480p","720p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":9,"videos":3,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"minTotalInputVideoDurationSeconds":2,"maxTotalInputVideoDurationSeconds":15,"inputMimeTypes":{"image":["image/jpeg","image/png","image/webp"],"video":["video/mp4","video/quicktime"]},"maxInputBytes":{"image":31457280}},
 "sd13-seedance-2.5": {"fields":["duration","aspect_ratio","resolution","generate_audio","reference_image_urls","reference_videos"],"parameters":[{"key":"duration","description":"出片时长，整数秒，范围 4–30。不传时为 5。","min":4,"max":30,"default":5},{"key":"aspect_ratio","description":"画幅比例，可选 auto / 21:9 / 16:9 / 4:3 / 1:1 / 3:4 / 9:16。不传时为 auto。带参考图时画面常跟随素材。","values":["auto","21:9","16:9","4:3","1:1","3:4","9:16"],"default":"auto"},{"key":"resolution","description":"清晰度，可选 480p / 720p。不传时为 480p。不支持 1080p。","values":["480p","720p"],"default":"480p"},{"key":"generate_audio","description":"是否生成音频，true / false。不传时为 true。","default":true}],"references":{"images":30,"videos":10,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"minTotalInputVideoDurationSeconds":2,"maxTotalInputVideoDurationSeconds":30,"inputMimeTypes":{"image":["image/jpeg","image/png","image/webp"],"video":["video/mp4","video/quicktime"]},"maxInputBytes":{"image":31457280,"video":209715200},"maxInputVideoDurationSeconds":30},
 "sd14-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios","first_image_url","last_image_url"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，可选 1:1 / 16:9 / 9:16。","values":["1:1","16:9","9:16"]},{"key":"resolution","description":"清晰度，固定 720p。可省略。","values":["720p"]}],"references":{"images":9,"videos":3,"audios":3},"frames":true,"framePairRequired":false,"allowFrameMediaMix":false,"maxOutputAndInputVideoDurationSeconds":25},
 "sd15-seedance-2.5": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，4–30。","min":4,"max":30},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]}],"references":{"images":30,"videos":0,"audios":10},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "sd15-seedance-2.0": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，4–15。","min":4,"max":15},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，可选 480p / 720p。","values":["480p","720p"]}],"references":{"images":9,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "gv3-grok-video-1.5": {"fields":["duration","aspect_ratio","resolution","reference_image_urls"],"parameters":[{"key":"duration","description":"时长秒数，3–15 的整数。","min":3,"max":15},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，固定 720p。可省略。","values":["720p"]}],"references":{"images":7,"videos":0,"audios":0},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false},
 "mm3-minimax-h3-2k": {"fields":["duration","aspect_ratio","resolution","reference_image_urls","reference_videos","reference_audios"],"parameters":[{"key":"duration","description":"时长秒数，只能传 15。","values":[15]},{"key":"aspect_ratio","description":"画幅比例，只支持 16:9 / 9:16 / 1:1。","values":["16:9","9:16","1:1"]},{"key":"resolution","description":"清晰度，固定 2k。可省略。","values":["2k"]}],"references":{"images":9,"videos":3,"audios":3},"frames":false,"framePairRequired":false,"allowFrameMediaMix":false,"videoObjects":true,"maxTotalInputVideoDurationSeconds":15,"maxInputAssets":10},
};
